#!/usr/bin/perl

##############################################################################
# This is a exmaple program to test the "external" output format with.  This
# routine simply writes our a lot file of what it has received. 
#
# Champ Clark III
# 08/05/2015
##############################################################################

my $filename = "/tmp/myprogram.$$"; 


$SIG{'INT'} = \&signal_handler;
$SIG{'TERM'} = \&signal_handler;
$SIG{'HUP'} = \&signal_handler;

open(MYFILE, ">> $filename") || die "Cannot open $filename!\n"; 

while (<>) {
    print MYFILE $_;
}

close(MYFILE); 
exit(0);


sub signal_handler {
close(MYFILE); 
exit(0);
}

